// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDww1Q4CVhr0BJnxE8bE6yEUk8Rulbq3kA',
    appId: '1:900763199493:web:fb204ee735dd47c6a5546c',
    messagingSenderId: '900763199493',
    projectId: 'leavs-722c4',
    authDomain: 'leavs-722c4.firebaseapp.com',
    storageBucket: 'leavs-722c4.appspot.com',
    measurementId: 'G-2H4G4J1G5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhFWQnie63gfOmhaxMjV4o4Nq1SVCnW3A',
    appId: '1:900763199493:android:52b5cfdf2e11b2cca5546c',
    messagingSenderId: '900763199493',
    projectId: 'leavs-722c4',
    storageBucket: 'leavs-722c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBMbcxlaKTLd8PWlFmWdoem-nEqGm_vAo',
    appId: '1:900763199493:ios:102deef3f3a5e9b3a5546c',
    messagingSenderId: '900763199493',
    projectId: 'leavs-722c4',
    storageBucket: 'leavs-722c4.appspot.com',
    androidClientId: '900763199493-rue6ngjlpin8sa1lg4m77a904fsaliih.apps.googleusercontent.com',
    iosClientId: '900763199493-db83pabc0dgk5r5pbah59njqmifguo2c.apps.googleusercontent.com',
    iosBundleId: 'com.starsphere.annualLeave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBMbcxlaKTLd8PWlFmWdoem-nEqGm_vAo',
    appId: '1:900763199493:ios:707f8a9bef51484ca5546c',
    messagingSenderId: '900763199493',
    projectId: 'leavs-722c4',
    storageBucket: 'leavs-722c4.appspot.com',
    iosClientId:
        '900763199493-1hv9avjckbv2uf4ifg6mal1m2vgjrqcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.annualLeave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDww1Q4CVhr0BJnxE8bE6yEUk8Rulbq3kA',
    appId: '1:900763199493:web:4d4b72b65946a11fa5546c',
    messagingSenderId: '900763199493',
    projectId: 'leavs-722c4',
    authDomain: 'leavs-722c4.firebaseapp.com',
    storageBucket: 'leavs-722c4.appspot.com',
    measurementId: 'G-GV1R0WY043',
  );
}